# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute the beta diversity between all sites
#'
#' @description
#' Compute the beta diversity between all sites for a specific presence-absence
#' matrix.
#'
#' @author
#' Kevin Cazelles
#'
#' @param mat_pa presence absence matrix (sites as rows and species as columns).
#'
#' @return
#' A dataframe with all the combinaison of site and the counts.
#'
betadiversity_core <- function(mat_pa) {
    .Call('_ecoocc_betadiversity_core', PACKAGE = 'ecoocc', mat_pa)
}

#' @title Co-occurrence
#'
#' @description
#' Compute the co-occurrence of all pairs of species.
#'
#' @author
#' Kevin Cazelles
#'
#' @param mat_pa presence absence matrix (sites as rows and species as columns).
#'
#' @return
#' A dataframe with all the combinaison of sites and the counts associated.
#'
cooccurrence_core <- function(mat_pa) {
    .Call('_ecoocc_cooccurrence_core', PACKAGE = 'ecoocc', mat_pa)
}

#' @title Compute the beta diversity two set of sites
#'
#' @description
#' Compute the beta diversity between all sites for a specific presence-absence
#' matrix.
#'
#' @author
#' Kevin Cazelles
#'
#' @param mat_pa1 presence absence matrix (sites as rows and species as columns) for time 1.
#' @param mat_pa2 presence absence matrix for time 2.
#'
#' @return
#' A dataframe with all the combinaison of sites and the counts associated.
#'
temporal_beta_core <- function(mat_pa1, mat_pa2) {
    .Call('_ecoocc_temporal_beta_core', PACKAGE = 'ecoocc', mat_pa1, mat_pa2)
}

